---
- hosts: network
  become: yes
  tasks:
  - name: fetch interfaces
    fetch: src=/etc/network/interfaces dest=ospf-unnumbered-flood-drain/{{ansible_hostname}}/ flat=yes

  - name: fetch Quagga daemons
    fetch: src=/etc/quagga/daemons dest=ospf-unnumbered-flood-drain/{{ansible_hostname}}/ flat=yes

  - name: fetch Quagga conf
    fetch: src=/etc/quagga/Quagga.conf dest=ospf-unnumbered-flood-drain/{{ansible_hostname}}/ flat=yes

  - name: fetch hsflowd conf
    fetch: src=/etc/hsflowd.conf dest=ospf-unnumbered-flood-drain/{{ansible_hostname}}/ flat=yes

- hosts: servers
  become: yes
  tasks:
  - name: fetch interfaces
    fetch: src=/etc/network/interfaces dest=ospf-unnumbered-flood-drain/{{ansible_hostname}}/ flat=yes
    ignore_errors: true
