---
- hosts: network
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=ospf-unnumbered-flood-drain/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: copy Quagga daemons
      copy: src=ospf-unnumbered-flood-drain/{{ansible_hostname}}/daemons dest=/etc/quagga/
    - name: copy Quagga conf
      copy: src=ospf-unnumbered-flood-drain/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/
    - name: reload networking
      command: ifreload -a
    - name: reload quagga
      service: name=quagga state=restarted

- hosts: leaf
  become: yes
  tasks:
    - name: copy hsflowd conf
      copy: src=ospf-unnumbered-flood-drain/{{ansible_hostname}}/hsflowd.conf dest=/etc/
    - name: Enable and restart hsflowd after pushing conf file
      systemd:
        name: hsflowd
        state: restarted
        enabled: yes

- hosts: servers
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=ospf-unnumbered-flood-drain/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: restarts servers with their new configuration
      shell: sleep 1 && shutdown -r 0
      async: 1
      poll: 0
      ignore_errors: true
    - name: Wait for everything to come back up
      local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
